inherit_from: .rubocop_todo.yml

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/*'

Style/RaiseArgs:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/*'

Style/AsciiComments:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 21

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 42

Metrics/PerceivedComplexity:
  Max: 21

Metrics/AbcSize:
  Max: 42

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'
