language: ruby
rvm:
  - 2.2.2
  - 2.3.1
before_install: gem install bundler -v 1.10.6

addons:
  code_climate:
    repo_token: 2e5471e8b02ecddecb5452adf02b990d8203698ab6ae919b40ce179f4a8a926a

after_script:
  - codeclimate-test-reporter < lcov.info
